rPiManager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls', namespace='core')),
    path('', include('users.urls', namespace='users')),
    path('', include('rpi.urls', namespace='rpi')),
    

]

rpi/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'rpi'

urlpatterns = [
   path('models/', views.rPiModelsList.as_view(), name='view_models'), 
   path('models/add-model/', views.rPiModelsAdd.as_view(), name='add_model'), 
   path('models/edit/<int:pk>', views.rPiModelsEdit.as_view(), name='edit_model'), 
   path('models/delete/<int:pk>', views.rPiModelsDelete.as_view(), name='delete_model'), 

   path('rpis/', views.rPiList.as_view(), name='view_rpis'), 
   path('rpis/add', views.rPiAdd.as_view(), name='add_rpi'), 
   path('rpis/<int:pk>', views.rPiViewrPi.as_view(), name='view_rpi'), 
   path('rpis/edit/<int:pk>', views.rPiEdit.as_view(), name='edit_rpi'), 
   path('rpis/delete/<int:pk>', views.rPiDelete.as_view(), name='delete_rpi'), 
   path('rpis/settings/<int:pk>', views.rPiSettings.as_view(), name='rpi_settings'), 
   path('rpis/deploy/<int:pk>', views.rPiDeploy.as_view(), name='rpi_deploy'), 
   path('rpis/search', views.rPiSearch.as_view(), name='rpi_search'), 
   path('rpis/check-in/<int:pk>', views.rPiCheckin.as_view(), name='rpi_checkin'), 
   path('rpis/key/upload/<int:pk>', views.rPiUploadKey.as_view(), name='rpi_upload_key'), 
   path('rpis/key/downlaod/<int:pk>', views.rPiDownloadKey.as_view(), name='rpi_download_key'), 
   path('rpis/deployed/', views.rPiDeployed.as_view(), name='rpi_deployed'), 
   path('rpis/deployed/search', views.rPiDeployedSearch.as_view(), name='rpi_deployed_search'), 
   path('rpis/connect/<int:pk>', views.rPiConnect.as_view(), name='rpi_connect'), 

   path('locations/', views.rPiViewLocations.as_view(), name='view_locations'), 
   path('locations/<int:pk>', views.rPiViewLocation.as_view(), name='view_location'), 
   path('locations/add/', views.rPiAddLocation.as_view(), name='add_location'), 
   path('locations/edit/<int:pk>', views.rPiEditLocation.as_view(), name='edit_location'), 
   path('locations/delete/<int:pk>', views.rPiDeleteLocation.as_view(), name='delete_location'),
   path('locations/search', views.rPiSearchLocation.as_view(), name='search_location'),
]
    
    

rpi/forms.py
from django.forms import ModelForm


from .models import RaspberryPiModel, RaspberryPi, RaspberryPiSettings, RaspberryPiURLs, Location

class RaspberryPiModelForm(ModelForm):
    class Meta:
        model = RaspberryPiModel
        fields = ['name']
        labels = {
            'name': 'Model'
        }
  

    def __init__(self, *args, **kwargs):
        super(RaspberryPiModelForm, self).__init__(*args, **kwargs)
        

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})

class RaspberryPiForm(ModelForm):
    class Meta:
        model = RaspberryPi
        fields = ['name', 'serial_number', 'model']

    def __init__(self, *args, **kwargs):
        super(RaspberryPiForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})

class RaspberryPiSettings(ModelForm):
    class Meta:
        model = RaspberryPiSettings
        fields = ['tab_switch_delay']

    def __init__(self, *args, **kwargs):
        super(RaspberryPiSettings, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})

class RaspberryPiURLs(ModelForm):
    class Meta:
        model = RaspberryPiURLs
        fields = ['name', 'url']

    def __init__(self, *args, **kwargs):
        super(RaspberryPiURLs, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})
class LocationForm(ModelForm):
    class Meta:
        model = Location
        fields = '__all__'
       
    def __init__(self, *args, **kwargs):
        super(LocationForm, self).__init__(*args, **kwargs)
        

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})

rpi/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.http import HttpResponse
from django.db.models.functions import Lower
from django.db.models import Q
from django.core.paginator import Paginator

from django.contrib.auth.mixins import LoginRequiredMixin

from django.conf import settings

from .models import RaspberryPiModel, RaspberryPi, Location, RaspberryPiDeployed
from .forms import RaspberryPiModelForm, RaspberryPiForm, LocationForm

# Create your views here.
class rPiModelsList(LoginRequiredMixin,View):
    def get(self, request):
        models = RaspberryPiModel.objects.all()
        context = { 
            'models': models
        }
        return render(request, 'rpi/models.html', context)

class rPiModelsAdd(LoginRequiredMixin, View):
    def get(self, request):
        form = RaspberryPiModelForm()
        context = {
            'form': form,
            'next': 'rpi:view_models'
        }
        return render(request,'rpi/add-model.html', context)

    def post(self, request):
        form = RaspberryPiModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('rpi:view_models')
        
        messages.error('Error creating model.')
        return render(request, 'rpi/add-model.html')

class rPiModelsEdit(LoginRequiredMixin, View):
    def get(self, request, pk):
        rpimodel = RaspberryPiModel.objects.get(id = pk)
       
        form = RaspberryPiModelForm(instance=rpimodel)
        
        context = {
            'form': form,
            'next': 'rpi:view_models'
        }
        return render(request,'rpi/add-model.html', context)

    def post(self, request, pk):
        model = RaspberryPiModel.objects.get(id = pk)
        form = RaspberryPiModelForm(request.POST,instance=model)
        if form.is_valid():
            form.save()
            return redirect('rpi:view_models')
        messages.error('Error updating model.')
        context = { 'form': form, 'next': 'rpi:view_models' }
        return render(request, 'rpi/add-model.html', context)


class rPiModelsDelete(LoginRequiredMixin,View):
    def delete(self, request, pk):
        model = RaspberryPiModel.objects.get(id = pk)
        model.delete()

        return HttpResponse('')
        #return render(request, 'rpi/partials/model-list.html', context)

class rPiList(LoginRequiredMixin, View):
    def get(self,request):
        order_by_param = request.GET.get('order_by','name')
        sort_order = request.GET.get('sort', 'asc')
      
        if sort_order == 'asc':
            rpis = RaspberryPi.objects.all().order_by(order_by_param)
        else:
            if order_by_param == 'name':
                rpis = RaspberryPi.objects.all().order_by(Lower('name').desc())
            else:
                rpis = RaspberryPi.objects.all().order_by('-checked_in')
        paginator = Paginator(rpis, settings.PER_PAGE)
        page_number = request.GET.get('page', 1)
        page_obj = paginator.get_page(page_number)
       
        context = { 'rpis': rpis, 
            'page_obj': page_obj,
            'order_by': order_by_param,
            'sort': sort_order
        }
        return render(request, 'rpi/raspberry_pis.html', context)

class rPiAdd(LoginRequiredMixin, View):
    def get(self, request):
        form = RaspberryPiForm()
        context = { 
            'form': form,
            'next': 'rpi:view_rpis'
        }
        return render(request, 'rpi/add-raspberry-pi.html', context)
    def post(self, request):
        form = RaspberryPiForm(request.POST)

        if form.is_valid:
            form.save()
            return redirect('rpi:view_rpis')    

        messages.error('Error creating model.')
        context = { 'form': form }
        return render(request, 'rpi/add-raspberry-pi.html', context)

class rPiViewrPi(LoginRequiredMixin, View):
    def get(self, request, pk):

        context = {
            'next': 'rpi:view_rpis'
        }
        return render(request, 'rpi/view_rpi.html', context)

class rPiEdit(LoginRequiredMixin, View):
    def get(self, request, pk):

        context = {
            'next': 'rpi:view_rpis'
        }
        return render(request, 'rpi/edit_rpi.html', context)

class rPiDelete(LoginRequiredMixin, View):
    def delete(self, request, pk):
        rpi = RaspberryPi.objects.get(id = pk)
        rpi.delete()

        return HttpResponse('')

class rPiSettings(LoginRequiredMixin, View):
    def get(self, request, pk):

        context = {
            'next': 'rpi:view_rpis'
        }
        return render(request, 'rpi/rpi_settings.html', context)

class rPiDeploy(LoginRequiredMixin, View):
    def get(self, request, pk):
        rpi = RaspberryPi.objects.get(id = pk)

        if rpi.deployed:
            return redirect('rpi:view_rpis')
        locations = Location.objects.all()

        paginator = Paginator(locations, settings.PER_PAGE)
        page_number = request.GET.get('page', 1)
        page_obj = paginator.get_page(page_number)
        context = {
            'rpi': rpi,
            'locations': locations,
            'page_obj': page_obj,
            'next': 'rpi:view_rpis'
        }
        return render(request, 'rpi/deploy_rpi.html', context)

    def post(self, request, pk):
        rpi = RaspberryPi.objects.get(id=pk)
        location = Location.objects.get(id=request.GET.get('loc'))

        deployed = RaspberryPiDeployed.objects.create(rpi=rpi, location=location)
        
        if deployed != None:
            rpi.deployed = True
            rpi.save()


        if request.META.get('HTTP_HX_REQUEST'):
            headers = {
                'HX-Redirect': 'rpi:view_rpis'
            }
            response = HttpResponse()
            response['HX-Redirect'] =  reverse_lazy('rpi:view_rpis')
            return response
    
        

class rPiCheckin(LoginRequiredMixin, View):
    def post(self, request, pk):
        rpi = RaspberryPi.objects.get(id=pk)
        rpi.deployed = False
        deployed = RaspberryPiDeployed.objects.get(rpi=rpi,active=True)
        deployed.active = False
        rpi.save()
        deployed.save()

        headers = {
                'HX-Redirect': 'rpi:view_rpis'
        }
        response = HttpResponse()
        response['HX-Redirect'] =  reverse_lazy('rpi:view_rpis')
        return response

class rPiDownloadKey(LoginRequiredMixin, View):
    def get(self, request, pk):

        context = {
            'next': 'rpi:view_rpis'
        }
        return render(request, 'rpi/rpi_settings.html', context)

class rPiUploadKey(LoginRequiredMixin, View):
    def get(self, request, pk):

        context = {
            'next': 'rpi:view_rpis'
        }
        return render(request, 'rpi/rpi_settings.html', context)

class rPiSearch(LoginRequiredMixin, View):
    def post(self, request):
       
        q = request.POST.get('search') if request.POST.get('search') != None and request.POST.get('search') != '' else ''
        rpis = RaspberryPi.objects.filter(Q(name__icontains=q))
        order_by_param = request.GET.get('order_by','name')
        sort_order = request.GET.get('sort', 'asc')
        if request.POST.get('search') != '':
            paginator = Paginator(rpis, rpis.count())    
        else:
            if sort_order == 'asc':
                if order_by_param == 'name':
                    rpis = RaspberryPi.objects.all().order_by(order_by_param)
                else:
                    rpis = RaspberryPi.objects.all().order_by('checked_in')
            else:
                if order_by_param == 'name':
                    rpis = RaspberryPi.objects.all().order_by(Lower('name').desc())
                else:
                    rpis = RaspberryPi.objects.all().order_by('-checked_in')
            
            paginator = Paginator(rpis, settings.PER_PAGE)

        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'page_obj': page_obj,
            'order_by': order_by_param,
            'sort': sort_order
           
        }
        return render(request, 'rpi/partials/raspberry-pi-list.html', context)

class rPiDeployed(LoginRequiredMixin, View):
    def get(self,request):
        order_by_param = request.GET.get('order_by','name')
        sort_order = request.GET.get('sort', 'asc')
        
        if sort_order == 'asc':
            if order_by_param == 'name':
                rpis = RaspberryPiDeployed.objects.filter(active = True).order_by('rpi__name')
               
            elif order_by_param == 'checked_in':
               rpis = RaspberryPiDeployed.objects.filter(active = True).order_by('checked_in')
            elif order_by_param == 'location':
                rpis = RaspberryPiDeployed.objects.filter(active = True).order_by('location__name')
        else:
            if order_by_param == 'name':
                rpis = RaspberryPiDeployed.objects.filter(active=True).order_by(Lower('rpi__name').desc())
            elif order_by_param == 'checked_in':
                rpis = RaspberryPiDeployed.objects.filter(active = True).order_by('-checked_in')
            elif order_by_param == 'location':
                rpis = RaspberryPiDeployed.objects.filter(active = True).order_by(Lower('location__name').desc())
        paginator = Paginator(rpis, settings.PER_PAGE)
        page_number = request.GET.get('page', 1)
        page_obj = paginator.get_page(page_number)
       
        context = { 
            'page_obj': page_obj,
            'order_by': order_by_param,
            'sort': sort_order
        }
        return render(request, 'rpi/deployed_raspberry_pis.html', context)

class rPiDeployedSearch(LoginRequiredMixin, View):
    def post(self, request):
       
        q = request.POST.get('search') if request.POST.get('search') != None and request.POST.get('search') != '' else ''

rpi/templates/rpi/partials/deploy-location-list.html
{% for location in page_obj %}
                                <tr>
                                    <td>
                                        {{location.name}} - {{location.city}}, {{location.state}}
                                    </td>
                                    <td style="text-align: right">
                                    <div class=" btn-group">
                                        <a title="Deploy"  hx-post="{% url 'rpi:rpi_deploy' rpi.id %}?loc={{location.id}}" class="btn btn-outline-info "><i class="fas fa-arrow-circle-right"></i> Deploy</a>                                        
                                    </div>
                                    </td>
                                </tr>
                            {% endfor %}

rpi/templates/rpi/partials/deployed-rpi-list.html
{% for rpi in page_obj %}
	<tr>
		<td>
             {{rpi.rpi.name}}
		</td>
        <td>
            {{rpi.location.name}}
        </td>
        <td>
            <div class=" ">
                <a title="Deploy" href="{% url 'rpi:view_rpis' %}" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-key-skeleton-left-right"></i>&nbsp;Connect</a>
                        {% comment %} <input class="form-check-input" type="checkbox" value="connect" name="connect" id="connect"  >
                        <label class="form-check-label" for="deployed"></label> {% endcomment %}
            </div>
        </td>
    
        {% if rpi.rpi.checked_in ==  null %}
            <td>
                Never
            </td>
        {% else %}
            <td>
                {{rpi.rpi.checked_in}}
            </td>
        {% endif %}
		
	</tr>
{% endfor %}

rpi/templates/rpi/partials/location-list.html
<ul class="list-group ">
    {% for location in locations %}
    <li class="list-group-item d-flex justify-content-between align-items-center shadow-sm">
       {{location.name}} - {{location.city}}, {{location.state}}
        <div class=" btn-group">
            <a title="Edit" href="{% url 'rpi:edit_location' location.id %}" class="btn btn-primary btn-sm"><i class="fa-solid fa-edit"></i> Edit</a>
            <span title="Delete" hx-delete="{% url 'rpi:delete_location' location.id %}" hx-target="#location-list" hx-confirm="Confirm?" class="btn btn-danger btn-sm"><i class="fa-solid fa-trash-can"></i> Delete</span>
        </div>
        
    </li>
{% endfor %}
</ul>

rpi/templates/rpi/partials/model-list.html
{% for model in models %}
	<tr>
		<td>
            {{model.name}}
		</td>
        <td></td>
		<td style="text-align: right">
            <div class=" btn-group">
                <a title="Edit" href="{% url 'rpi:edit_model' model.id %}" class="btn btn-primary btn-sm"><i class="fa-solid fa-edit"></i> Edit</a>
                <span title="Delete" hx-delete="{% url 'rpi:delete_model' model.id %}"  class="btn btn-danger btn-sm"><i class="fa-solid fa-trash-can"></i> Delete</span>
            </div>
		</td>
	</tr>
{% endfor %}

rpi/templates/rpi/partials/raspberry-pi-list.html
{% for rpi in rpis %}
	<tr>
		<td>
             {{rpi.name}}
		</td>
        <td>
            {{rpi.serial_number}}
        </td>
        <td>
             <div class="form-outline  form-check ">
                        <input class="form-check-input" type="checkbox" value="deployed" name="deployed" id="deployed"  {% if rpi.deployed %} checked {% endif %} disabled>
                        <label class="form-check-label" for="deployed"></label>
                    </div>
        </td>
    
        {% if rpi.checked_in ==  null %}
            <td>
                Never
            </td>
        {% else %}
            <td>
                {{rpi.checked_in}}
            </td>
        {% endif %}
		<td style="text-align: right">
           <div class=" btn-group">
            <a title="Edit" href="{% url 'rpi:edit_rpi' rpi.id %}" class="btn btn-primary btn"><i class="fa-solid fa-edit"></i> </a>
            <a title="Details" href="{% url 'rpi:view_rpi' rpi.id %}" class="btn btn-success btn"><i class="fas fa-list-alt"></i> </a>
            <span title="Delete" hx-delete="{% url 'rpi:delete_rpi' rpi.id %}" class="btn btn-danger btn"><i class="fa-solid fa-trash-can"></i></span>
            <a title="Settings" href="{% url 'rpi:rpi_settings' rpi.id %}" class="btn btn-outline-info btn"><i class="fas fa-cog"></i></a>
            <a  title="Upload Key" href="{% url 'rpi:rpi_upload_key' rpi.id %}" class="btn btn-outline-info btn"><i class="fas fa-upload"></i></a>
            <a title="Download Key" href="{% url 'rpi:rpi_download_key' rpi.id %}" class="btn btn-outline-info btn"><i class="fas fa-download"></i></a>
           
        </div>
		</td>
        <td>
             {% if rpi.deployed %}
                <a title="Check-in" href="{% url 'rpi:rpi_checkin' rpi.id %}" class="btn btn-outline-info btn"><i class="fas fa-arrow-circle-left"></i>&nbsp;Check-in</a>
            {% else %}
                <a title="Deploy" href="{% url 'rpi:rpi_deploy' rpi.id %}" class="btn btn-outline-info btn"><i class="fas fa-arrow-circle-right"></i>&nbsp;Deploy</a>
             {% endif %}
        
        </td>
	</tr>
{% endfor %}
{% comment %} <ul class="list-group ">
    {% for rpi in rpis %}
    <li class="list-group-item d-flex justify-content-between align-items-center shadow-sm">
       {{rpi.name}}
        <div class=" btn-group">
            <a title="Edit" href="{% url 'rpi:edit_rpi' rpi.id %}" class="btn btn-primary btn-sm"><i class="fa-solid fa-edit"></i> </a>
            <a title="Details" href="{% url 'rpi:view_rpi' rpi.id %}" class="btn btn-success btn-sm"><i class="fas fa-list-alt"></i> </a>
            <span title="Delete" hx-delete="{% url 'rpi:delete_rpi' rpi.id %}" hx-target="#rpi-list" hx-confirm="Confirm?" class="btn btn-danger btn-sm"><i class="fa-solid fa-trash-can"></i></span>
            <a title="Settings" href="{% url 'rpi:rpi_settings' rpi.id %}" class="btn btn-outline-info btn-sm"><i class="fas fa-cog"></i></a>
            <a  title="Upload Key" href="{% url 'rpi:rpi_upload_key' rpi.id %}" class="btn btn-outline-info btn-sm"><i class="fas fa-upload"></i></a>
            <a title="Download Key" href="{% url 'rpi:rpi_download_key' rpi.id %}" class="btn btn-outline-info btn-sm"><i class="fas fa-download"></i></a>
            {% if rpi.deployed %}
                <a title="Check-in" href="{% url 'rpi:rpi_checkin' rpi.id %}" class="btn btn-outline-info btn-sm"><i class="fas fa-arrow-circle-left"></i>&nbsp;Check-in</a>
            {% else %}
                <a title="Deploy" href="{% url 'rpi:rpi_deploy' rpi.id %}" class="btn btn-outline-info btn-sm"><i class="fas fa-arrow-circle-right"></i>&nbsp;Deploy</a>
             {% endif %}
        
        </div>

       
    </li>
{% endfor %}
</ul> {% endcomment %}