rPiManager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls', namespace='core')),
    path('', include('users.urls', namespace='users')),
    path('', include('rpi.urls', namespace='rpi')),
    

]

rpi/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'rpi'

urlpatterns = [
   path('models/', views.rPiModelsList.as_view(), name='view_models'), 
   path('models/add-model/', views.rPiModelsAdd.as_view(), name='add_model'), 
   path('models/edit/<int:pk>', views.rPiModelsEdit.as_view(), name='edit_model'), 
   path('models/delete/<int:pk>', views.rPiModelsDelete.as_view(), name='delete_model'), 

   path('rpis/', views.rPiList.as_view(), name='view_rpis'), 
   path('rpis/add', views.rPiAdd.as_view(), name='add_rpi'), 
   path('rpis/<int:pk>', views.rPiViewrPi.as_view(), name='view_rpi'), 
   path('rpis/edit/<int:pk>', views.rPiEdit.as_view(), name='edit_rpi'), 
   path('rpis/delete/<int:pk>', views.rPiDelete.as_view(), name='delete_rpi'), 
   path('rpis/settings/<int:pk>', views.rPiSettings.as_view(), name='rpi_settings'), 
   path('rpis/deploy/<int:pk>', views.rPiDeploy.as_view(), name='rpi_deploy'), 
   path('rpis/search', views.rPiSearch.as_view(), name='rpi_search'), 
   path('rpis/check-in/<int:pk>', views.rPiCheckin.as_view(), name='rpi_checkin'), 
   path('rpis/key/upload/<int:pk>', views.rPiUploadKey.as_view(), name='rpi_upload_key'), 
   path('rpis/key/downlaod/<int:pk>', views.rPiDownloadKey.as_view(), name='rpi_download_key'), 
   path('rpis/deployed/', views.rPiDeployed.as_view(), name='rpi_deployed'), 
   path('rpis/deployed/search', views.rPiDeployedSearch.as_view(), name='rpi_deployed_search'), 
   path('rpis/connect/<int:pk>', views.rPiConnect.as_view(), name='rpi_connect'), 

   path('locations/', views.rPiViewLocations.as_view(), name='view_locations'), 
   path('locations/<int:pk>', views.rPiViewLocation.as_view(), name='view_location'), 
   path('locations/add/', views.rPiAddLocation.as_view(), name='add_location'), 
   path('locations/edit/<int:pk>', views.rPiEditLocation.as_view(), name='edit_location'), 
   path('locations/delete/<int:pk>', views.rPiDeleteLocation.as_view(), name='delete_location'),
   path('locations/search', views.rPiSearchLocation.as_view(), name='search_location'),
]
    
    

core/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
   pass

class UserProfile(models.Model):
   full_name = models.CharField(max_length=250,null=True,blank=True)
   user = models.OneToOneField(User,on_delete=models.CASCADE)

   def __str__(self):
      return self.full_name

class UserSettings(models.Model):
   owner = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
   
class PasswordToken(models.Model):
    token = models.UUIDField(null=False)
    email = models.EmailField(null=False, blank=False)
    name = models.CharField(max_length=200, null=True)
    last_name = models.CharField(max_length=200, null=True)
    user_id = models.PositiveIntegerField(null=True)
    is_staff = models.BooleanField(null=False, default=False)
    token_life = models.PositiveIntegerField(null=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.token)

rpi/forms.py
from django.forms import ModelForm


from .models import RaspberryPiModel, RaspberryPi, RaspberryPiSettings, RaspberryPiURLs, Location

class RaspberryPiModelForm(ModelForm):
    class Meta:
        model = RaspberryPiModel
        fields = ['name']
        labels = {
            'name': 'Model'
        }
  

    def __init__(self, *args, **kwargs):
        super(RaspberryPiModelForm, self).__init__(*args, **kwargs)
        

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})

class RaspberryPiForm(ModelForm):
    class Meta:
        model = RaspberryPi
        fields = ['name', 'serial_number', 'model']

    def __init__(self, *args, **kwargs):
        super(RaspberryPiForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})

class RaspberryPiSettings(ModelForm):
    class Meta:
        model = RaspberryPiSettings
        fields = ['tab_switch_delay']

    def __init__(self, *args, **kwargs):
        super(RaspberryPiSettings, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})

class RaspberryPiURLs(ModelForm):
    class Meta:
        model = RaspberryPiURLs
        fields = ['name', 'url']

    def __init__(self, *args, **kwargs):
        super(RaspberryPiURLs, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})
class LocationForm(ModelForm):
    class Meta:
        model = Location
        fields = '__all__'
       
    def __init__(self, *args, **kwargs):
        super(LocationForm, self).__init__(*args, **kwargs)
        

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})

rpi/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.http import HttpResponse
from django.db.models.functions import Lower
from django.db.models import Q
from django.core.paginator import Paginator

from django.contrib.auth.mixins import LoginRequiredMixin

from django.conf import settings

from .models import RaspberryPiModel, RaspberryPi, Location, RaspberryPiDeployed
from .forms import RaspberryPiModelForm, RaspberryPiForm, LocationForm

# Create your views here.
class rPiModelsList(LoginRequiredMixin,View):
    def get(self, request):
        models = RaspberryPiModel.objects.all()
        context = { 
            'models': models
        }
        return render(request, 'rpi/models.html', context)

class rPiModelsAdd(LoginRequiredMixin, View):
    def get(self, request):
        form = RaspberryPiModelForm()
        context = {
            'form': form,
            'next': 'rpi:view_models'
        }
        return render(request,'rpi/add-model.html', context)

    def post(self, request):
        form = RaspberryPiModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('rpi:view_models')
        
        messages.error('Error creating model.')
        return render(request, 'rpi/add-model.html')

class rPiModelsEdit(LoginRequiredMixin, View):
    def get(self, request, pk):
        rpimodel = RaspberryPiModel.objects.get(id = pk)
       
        form = RaspberryPiModelForm(instance=rpimodel)
        
        context = {
            'form': form,
            'next': 'rpi:view_models'
        }
        return render(request,'rpi/add-model.html', context)

    def post(self, request, pk):
        model = RaspberryPiModel.objects.get(id = pk)
        form = RaspberryPiModelForm(request.POST,instance=model)
        if form.is_valid():
            form.save()
            return redirect('rpi:view_models')
        messages.error('Error updating model.')
        context = { 'form': form, 'next': 'rpi:view_models' }
        return render(request, 'rpi/add-model.html', context)


class rPiModelsDelete(LoginRequiredMixin,View):
    def delete(self, request, pk):
        model = RaspberryPiModel.objects.get(id = pk)
        model.delete()

        return HttpResponse('')
        #return render(request, 'rpi/partials/model-list.html', context)

class rPiList(LoginRequiredMixin, View):
    def get(self,request):
        order_by_param = request.GET.get('order_by','name')
        sort_order = request.GET.get('sort', 'asc')
      
        if sort_order == 'asc':
            rpis = RaspberryPi.objects.all().order_by(order_by_param)
        else:
            if order_by_param == 'name':
                rpis = RaspberryPi.objects.all().order_by(Lower('name').desc())
            else:
                rpis = RaspberryPi.objects.all().order_by('-checked_in')
        paginator = Paginator(rpis, settings.PER_PAGE)
        page_number = request.GET.get('page', 1)
        page_obj = paginator.get_page(page_number)
       
        context = { 'rpis': rpis, 
            'page_obj': page_obj,
            'order_by': order_by_param,
            'sort': sort_order
        }
        return render(request, 'rpi/raspberry_pis.html', context)

class rPiAdd(LoginRequiredMixin, View):
    def get(self, request):
        form = RaspberryPiForm()
        context = { 
            'form': form,
            'next': 'rpi:view_rpis'
        }
        return render(request, 'rpi/add-raspberry-pi.html', context)
    def post(self, request):
        form = RaspberryPiForm(request.POST)

        if form.is_valid:
            form.save()
            return redirect('rpi:view_rpis')    

        messages.error('Error creating model.')
        context = { 'form': form }
        return render(request, 'rpi/add-raspberry-pi.html', context)

class rPiViewrPi(LoginRequiredMixin, View):
    def get(self, request, pk):

        context = {
            'next': 'rpi:view_rpis'
        }
        return render(request, 'rpi/view_rpi.html', context)

class rPiEdit(LoginRequiredMixin, View):
    def get(self, request, pk):

        context = {
            'next': 'rpi:view_rpis'
        }
        return render(request, 'rpi/edit_rpi.html', context)

class rPiDelete(LoginRequiredMixin, View):
    def delete(self, request, pk):
        rpi = RaspberryPi.objects.get(id = pk)
        rpi.delete()

        return HttpResponse('')

class rPiSettings(LoginRequiredMixin, View):
    def get(self, request, pk):

        context = {
            'next': 'rpi:view_rpis'
        }
        return render(request, 'rpi/rpi_settings.html', context)

class rPiDeploy(LoginRequiredMixin, View):
    def get(self, request, pk):
        rpi = RaspberryPi.objects.get(id = pk)

        if rpi.deployed:
            return redirect('rpi:view_rpis')
        locations = Location.objects.all()

        paginator = Paginator(locations, settings.PER_PAGE)
        page_number = request.GET.get('page', 1)
        page_obj = paginator.get_page(page_number)
        context = {
            'rpi': rpi,
            'locations': locations,
            'page_obj': page_obj,
            'next': 'rpi:view_rpis'
        }
        return render(request, 'rpi/deploy_rpi.html', context)

    def post(self, request, pk):
        rpi = RaspberryPi.objects.get(id=pk)
        location = Location.objects.get(id=request.GET.get('loc'))

        deployed = RaspberryPiDeployed.objects.create(rpi=rpi, location=location)
        
        if deployed != None:
            rpi.deployed = True
            rpi.save()


        if request.META.get('HTTP_HX_REQUEST'):
            headers = {
                'HX-Redirect': 'rpi:view_rpis'
            }
            response = HttpResponse()
            response['HX-Redirect'] =  reverse_lazy('rpi:view_rpis')
            return response
    
        

class rPiCheckin(LoginRequiredMixin, View):
    def post(self, request, pk):
        rpi = RaspberryPi.objects.get(id=pk)
        rpi.deployed = False
        deployed = RaspberryPiDeployed.objects.get(rpi=rpi,active=True)
        deployed.active = False
        rpi.save()
        deployed.save()

        headers = {
                'HX-Redirect': 'rpi:view_rpis'
        }
        response = HttpResponse()
        response['HX-Redirect'] =  reverse_lazy('rpi:view_rpis')
        return response

class rPiDownloadKey(LoginRequiredMixin, View):
    def get(self, request, pk):

        context = {
            'next': 'rpi:view_rpis'
        }
        return render(request, 'rpi/rpi_settings.html', context)

class rPiUploadKey(LoginRequiredMixin, View):
    def get(self, request, pk):

        context = {
            'next': 'rpi:view_rpis'
        }
        return render(request, 'rpi/rpi_settings.html', context)

class rPiSearch(LoginRequiredMixin, View):
    def post(self, request):
       
        q = request.POST.get('search') if request.POST.get('search') != None and request.POST.get('search') != '' else ''
        rpis = RaspberryPi.objects.filter(Q(name__icontains=q))
        order_by_param = request.GET.get('order_by','name')
        sort_order = request.GET.get('sort', 'asc')
        if request.POST.get('search') != '':
            paginator = Paginator(rpis, rpis.count())    
        else:
            if sort_order == 'asc':
                if order_by_param == 'name':
                    rpis = RaspberryPi.objects.all().order_by(order_by_param)
                else:
                    rpis = RaspberryPi.objects.all().order_by('checked_in')
            else:
                if order_by_param == 'name':
                    rpis = RaspberryPi.objects.all().order_by(Lower('name').desc())
                else:
                    rpis = RaspberryPi.objects.all().order_by('-checked_in')
            
            paginator = Paginator(rpis, settings.PER_PAGE)

        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'page_obj': page_obj,
            'order_by': order_by_param,
            'sort': sort_order
           
        }
        return render(request, 'rpi/partials/raspberry-pi-list.html', context)

class rPiDeployed(LoginRequiredMixin, View):
    def get(self,request):
        order_by_param = request.GET.get('order_by','name')
        sort_order = request.GET.get('sort', 'asc')
        
        if sort_order == 'asc':
            if order_by_param == 'name':
                rpis = RaspberryPiDeployed.objects.filter(active = True).order_by('rpi__name')
               
            elif order_by_param == 'checked_in':
               rpis = RaspberryPiDeployed.objects.filter(active = True).order_by('checked_in')
            elif order_by_param == 'location':
                rpis = RaspberryPiDeployed.objects.filter(active = True).order_by('location__name')
        else:
            if order_by_param == 'name':
                rpis = RaspberryPiDeployed.objects.filter(active=True).order_by(Lower('rpi__name').desc())
            elif order_by_param == 'checked_in':
                rpis = RaspberryPiDeployed.objects.filter(active = True).order_by('-checked_in')
            elif order_by_param == 'location':
                rpis = RaspberryPiDeployed.objects.filter(active = True).order_by(Lower('location__name').desc())
        paginator = Paginator(rpis, settings.PER_PAGE)
        page_number = request.GET.get('page', 1)
        page_obj = paginator.get_page(page_number)
       
        context = { 
            'page_obj': page_obj,
            'order_by': order_by_param,
            'sort': sort_order
        }
        return render(request, 'rpi/deployed_raspberry_pis.html', context)

class rPiDeployedSearch(LoginRequiredMixin, View):
    def post(self, request):
       
        q = request.POST.get('search') if request.POST.get('search') != None and request.POST.get('search') != '' else ''

rpi/templates/rpi/add-model.html
{% extends "navbar.html" %}

{% block content %}
<div class="container">
    <div class="justify-content-center mt-5">
        
        <div class="card shadow-sm login-card col-lg-6 col-md-6 col-sm-6 mx-auto" >
            <div class="card-header">
                Raspberry Pi Model
            </div>
            <div class="card-body  ">
                <form  method="POST" >
                    {% csrf_token %}
                     {% for field in form %}
                     <div class="form-outline mb-4">
                        <label for="formInput#text">{{field.label}} </label>
                        {{field}}
                      </div>
                      {% endfor %}
                    

                    <!-- Submit button -->
                    <button type="submit" class="btn btn-primary btn-block mb-4">Submit</button>
                    <a href="{% url next %}" class="btn btn-danger btn-block mb-4">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

rpi/templates/rpi/add-raspberry-pi.html
{% extends "navbar.html" %}

{% block content %}
<div class="container">
    <div class="justify-content-center mt-5">
        
        <div class="card shadow-sm login-card col-lg-6 col-md-6 col-sm-6 mx-auto" >
            <div class="card-header">
                Raspberry Pi 
            </div>
            <div class="card-body  ">
                <form  method="POST" >
                    {% csrf_token %}
                     {% for field in form %}
                     <div class="form-outline mb-4">
                        <label for="formInput#text">{{field.label}} </label>
                        {{field}}
                      </div>
                      {% endfor %}
                    

                    <!-- Submit button -->
                    <button type="submit" class="btn btn-primary btn-block mb-4">Submit</button>
                    <a href="{% url next %}" class="btn btn-danger btn-block mb-4">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

rpi/templates/rpi/deploy_rpi.html
{% extends "navbar.html" %}

{% block content %}

<div class="container">
    <div class="justify-content-center mt-5">
        
        <div class="card shadow-sm login-card col-lg-8 col-md-6 col-sm-6 mx-auto" >
            <div class="card-header">
                Deploy
            </div>
            <div class="card-body  ">
                {% if form.errors %}
                    <p>{{ form.non_field_errors }}</p>
                {% endif %}
                <form  method="POST"  >
                    {% csrf_token %}
                    
                    <div class="form-outline mb-4">
                        <input type="text" id="name" name="name" class="form-control" value="{{rpi.name}}" disabled/>
                        <label class="form-label" for="name">Raspberry Pi</label>
                    </div>

                    <div class="input-group">
                        <input id="search" class="form-control" type="search" 
                            name="search" placeholder="Begin Typing To Search Locations..." 
                            hx-post="{% url 'rpi:search_location' %}?page={{page_obj.number}}" 
                            hx-trigger="keyup changed delay:500ms, search" 
                            hx-target="#search-results" 
                            hx-indicator=".htmx-indicator">
                      
                    </div>
                    
                    <span class="htmx-indicator"> 
                       Searching... 
                    </span> 
                    <div class="table-responsive-md ">
                        <table class="table table-striped table-hover  table-list-search">
                        <thead>
                            <tr>
                            <th colspan="3">
                                Locations
                            </th>

                            </tr>
                        </thead>
                        <tbody id="search-results"  >
                                {% include 'rpi/partials/deploy-location-list.html' %}
                        </tbody>
                        </table>
	                </div>
       
                    <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
                    <br>
                    <!-- Submit button -->
                    <button type="submit" class="btn btn-primary btn-block mb-4">Submit</button>
                    <input type="hidden" name="next" value="{{ next }}">
                    
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

rpi/templates/rpi/deployed_raspberry_pis.html
{% extends 'navbar.html' %}

{% block content %}

<div class="col mt-5">
  
  <div class="border p-3">
      <div class="input-group">
        <input id="search" class="form-control" type="search" 
            name="search" placeholder="Begin Typing To Search rPis..." 
            hx-post="{% url 'rpi:rpi_deployed_search' %}?page={{page_obj.number}}&order_by={{order_by}}&sort={{sort}}" 
            hx-trigger="keyup changed delay:500ms, search" 
            hx-target="#rPiTable" 
            hx-indicator=".htmx-indicator">
      </div>
                    
        <span class="htmx-indicator"> 
          Searching... 
        </span> 
      <div class="table-responsive-md ">
        <table class="table table-striped table-hover align-middle table-list-search">
          <thead>
            <tr>
              <th>
                Name &nbsp;<a href="?order_by=name"><i class="fas fa-angle-up"></i></a>&nbsp;<a href="?order_by=name&sort=desc"><i class="fas fa-angle-down"></i></a>
              </th>
              <th>
                Location &nbsp;<a href="?order_by=location"><i class="fas fa-angle-up"></i></a>&nbsp;<a href="?order_by=location&sort=desc"><i class="fas fa-angle-down"></i></a>
              </th>
              <th>
                Connect
              </th>
              <th >
                Last Checked In&nbsp;<a href="?order_by=checked_in"><i class="fas fa-angle-up"></i></a>&nbsp;<a href="?order_by=checked_in&sort=desc"><i class="fas fa-angle-down"></i></a>
              </th>
			      </tr>
          </thead>
          <tbody id="rPiTable" hx-confirm="Are you sure?" hx-target="closest tr" hx-swap="outerHTML swap:1s">
                {% include 'rpi/partials/deployed-rpi-list.html' %} 
          </tbody>
        </table>
	      </div>
        <div class="pagination">
          <span class="step-links">
            {% if page_obj.has_previous %}
              <a href="?page=1">&laquo; first</a>
              <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
            </span>
        </div>
      </div>
     
    
  </div>
</div>

{% endblock %}

rpi/templates/rpi/edit_rpi.html
{% extends "navbar.html" %}

{% block content %}
<div class="container">
    <div class="justify-content-center mt-5">
        
        <div class="card shadow-sm login-card col-lg-6 col-md-6 col-sm-6 mx-auto" >
            <div class="card-header">
                Raspberry Pi 
            </div>
            <div class="card-body  ">
                <form  method="POST" >
                    {% csrf_token %}
                     {% for field in form %}
                     <div class="form-outline mb-4">
                        <label for="formInput#text">{{field.label}} </label>
                        {{field}}
                      </div>
                      {% endfor %}
                    

                    <!-- Submit button -->
                    <button type="submit" class="btn btn-primary btn-block mb-4">Submit</button>
                    <a href="{% url next %}" class="btn btn-danger btn-block mb-4">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

rpi/templates/rpi/location_form.html
{% extends "navbar.html" %}

{% block content %}
<div class="container">
    <div class="justify-content-center mt-5">
        
        <div class="card shadow-sm login-card col-lg-6 col-md-6 col-sm-6 mx-auto" >
            <div class="card-header">
                Location
            </div>
            <div class="card-body  ">
                <form  method="POST" >
                    {% csrf_token %}
                     {% for field in form %}
                     <div class="form-outline mb-4">
                        <label for="formInput#text">{{field.label}} </label>
                        {{field}}
                      </div>
                      {% endfor %}
                    

                    <!-- Submit button -->
                    <button type="submit" class="btn btn-primary btn-block mb-4">Submit</button>
                    <a href="{% url next %}" class="btn btn-danger btn-block mb-4">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

rpi/templates/rpi/locations.html
{% extends 'navbar.html' %}

{% block content %}

<div class="col mt-5">
<h1>Locations</h1>
  <hr>
  <div class="action-buttons pb-3">
      <a href="{% url 'rpi:add_location' %}" class="btn btn-primary"><i class="fa-solid fa-plus"></i> Create New</a>
  </div>
  <div class="border p-3">
   
      <div class="row">
        <div class="col" id="location-list">
            {% include 'rpi/partials/location-list.html' %} 
        </div>
      </div>
    
  </div>
</div>

{% endblock %}

rpi/templates/rpi/models.html
{% extends 'navbar.html' %}

{% block content %}

<div class="col mt-5">
 
  <div class="action-buttons pb-3">
      <a href="{% url 'rpi:add_model' %}" class="btn btn-primary"><i class="fa-solid fa-plus"></i> Add Model</a>
  </div>
  <div class="border p-3">
   
      <div class="table-responsive-md ">
        <table class="table table-striped table-hover  table-list-search">
          <thead>
            <tr>
              <th colspan="3">
                Models
              </th>

            </tr>
          </thead>
          <tbody hx-confirm="Are you sure?" hx-target="closest tr" hx-swap="outerHTML swap:1s">
                {% include 'rpi/partials/model-list.html' %} 
          </tbody>
        </table>
	      </div>
       
      </div>
    
  </div>
</div>

{% endblock %}

rpi/templates/rpi/raspberry_pis.html
{% extends 'navbar.html' %}

{% block content %}

<div class="col mt-5">
  <div class="action-buttons pb-3">
      <a href="{% url 'rpi:add_rpi' %}" class="btn btn-primary"><i class="fa-solid fa-plus"></i> Create New</a>
  </div>
  <div class="border p-3">
      <div class="input-group">
        <input id="search" class="form-control" type="search" 
            name="search" placeholder="Begin Typing To Search rPis..." 
            hx-post="{% url 'rpi:rpi_search' %}?page={{page_obj.number}}&order_by={{order_by}}&sort={{sort}}" 
            hx-trigger="keyup changed delay:500ms, search" 
            hx-target="#rPiTable" 
            hx-indicator=".htmx-indicator">
      </div>
                    
        <span class="htmx-indicator"> 
          Searching... 
        </span> 
      <div class="table-responsive-md ">
        <table class="table table-striped table-hover align-middle table-list-search">
          <thead>
            <tr>
              <th>
                Name &nbsp;<a href="?order_by=name"><i class="fas fa-angle-up"></i></a>&nbsp;<a href="?order_by=name&sort=desc"><i class="fas fa-angle-down"></i></a>
              </th>
              <th>
                Serial Number
              </th>
              <th>
                Deployed
              </th>
              <th >
                Last Checked In&nbsp;<a href="?order_by=checked_in"><i class="fas fa-angle-up"></i></a>&nbsp;<a href="?order_by=checked_in&sort=desc"><i class="fas fa-angle-down"></i></a>
              </th>
			      </tr>
          </thead>
          <tbody id="rPiTable" hx-confirm="Are you sure?" hx-target="closest tr" hx-swap="outerHTML swap:1s">
                {% include 'rpi/partials/raspberry-pi-list.html' %} 
          </tbody>
        </table>
	      </div>

        <nav aria-label="Page navigation example">
        
  <ul class="pagination">
      
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
     {% endif %}
     {% if page_obj.has_next %}
    <li>
      <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
        
    
  </div>
</div>

{% endblock %}

rpi/templates/rpi/rpi_settings.html
{% extends "navbar.html" %}

{% block content %}
<div class="container">
    <div class="justify-content-center mt-5">
        
        <div class="card shadow-sm login-card col-lg-6 col-md-6 col-sm-6 mx-auto" >
            <div class="card-header">
                Raspberry Pi 
            </div>
            <div class="card-body  ">
                <form  method="POST" >
                    {% csrf_token %}
                     {% for field in form %}
                     <div class="form-outline mb-4">
                        <label for="formInput#text">{{field.label}} </label>
                        {{field}}
                      </div>
                      {% endfor %}
                    

                    <!-- Submit button -->
                    <button type="submit" class="btn btn-primary btn-block mb-4">Submit</button>
                    <a href="{% url next %}" class="btn btn-danger btn-block mb-4">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

rpi/templates/rpi/view_rpi.html
{% extends "navbar.html" %}

{% block content %}
<div class="container">
    <div class="justify-content-center mt-5">
        
        <div class="card shadow-sm login-card col-lg-6 col-md-6 col-sm-6 mx-auto" >
            <div class="card-header">
                Raspberry Pi 
            </div>
            <div class="card-body  ">
                <form  method="POST" >
                    {% csrf_token %}
                     {% for field in form %}
                     <div class="form-outline mb-4">
                        <label for="formInput#text">{{field.label}} </label>
                        {{field}}
                      </div>
                      {% endfor %}
                    

                    <!-- Submit button -->
                    <button type="submit" class="btn btn-primary btn-block mb-4">Submit</button>
                    <a href="{% url next %}" class="btn btn-danger btn-block mb-4">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}