rPiManager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls', namespace='core')),
    path('', include('users.urls', namespace='users')),
    path('', include('rpi.urls', namespace='rpi')),
    

]

rpi/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'rpi'

urlpatterns = [
   path('models/', views.rPiModelsList.as_view(), name='view_models'), 
   path('models/add-model/', views.rPiModelsAdd.as_view(), name='add_model'), 
   path('models/edit/<int:pk>', views.rPiModelsEdit.as_view(), name='edit_model'), 
   path('models/delete/<int:pk>', views.rPiModelsDelete.as_view(), name='delete_model'), 

   path('rpis/', views.rPiList.as_view(), name='view_rpis'), 
   path('rpis/add', views.rPiAdd.as_view(), name='add_rpi'), 
   path('rpis/<int:pk>', views.rPiViewrPi.as_view(), name='view_rpi'), 
   path('rpis/edit/<int:pk>', views.rPiEdit.as_view(), name='edit_rpi'), 
   path('rpis/delete/<int:pk>', views.rPiDelete.as_view(), name='delete_rpi'), 
   path('rpis/settings/<int:pk>', views.rPiSettings.as_view(), name='rpi_settings'), 
   path('rpis/deploy/<int:pk>', views.rPiDeploy.as_view(), name='rpi_deploy'), 
   path('rpis/search', views.rPiSearch.as_view(), name='rpi_search'), 
   path('rpis/check-in/<int:pk>', views.rPiCheckin.as_view(), name='rpi_checkin'), 
   path('rpis/key/upload/<int:pk>', views.rPiUploadKey.as_view(), name='rpi_upload_key'), 
   path('rpis/key/downlaod/<int:pk>', views.rPiDownloadKey.as_view(), name='rpi_download_key'), 
   path('rpis/deployed/', views.rPiDeployed.as_view(), name='rpi_deployed'), 
   path('rpis/deployed/search', views.rPiDeployedSearch.as_view(), name='rpi_deployed_search'), 
   path('rpis/connect/<int:pk>', views.rPiConnect.as_view(), name='rpi_connect'), 

   path('locations/', views.rPiViewLocations.as_view(), name='view_locations'), 
   path('locations/<int:pk>', views.rPiViewLocation.as_view(), name='view_location'), 
   path('locations/add/', views.rPiAddLocation.as_view(), name='add_location'), 
   path('locations/edit/<int:pk>', views.rPiEditLocation.as_view(), name='edit_location'), 
   path('locations/delete/<int:pk>', views.rPiDeleteLocation.as_view(), name='delete_location'),
   path('locations/search', views.rPiSearchLocation.as_view(), name='search_location'),
]
    
    

users/urls.py
from django.contrib import admin
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
   path('profile/', views.ProfileViewProfile.as_view(), name='view_profile'), 
   path('register/', views.ProfileRegisterUser.as_view(), name='register_user'),
   path('forgot-password/', views.ProfileForgotPassword.as_view(), name='forgot_password'),
   path('users/', views.UsersViewAll.as_view(), name='view_users'),
    path('users/<int:pk>/', views.UsersViewUser.as_view(), name='user_view'),
    path('users/edit/<int:pk>/', views.UsersEditUser.as_view(), name='user_edit'),
    path('users/delete/<int:pk>/', views.UsersDeleteUser.as_view(), name='user_delete'),
    path('users/create/', views.UsersCreateUser.as_view(), name='user_create'),

    path('users/invite/', views.UsersInviteUser.as_view(), name='user_invite'),
    path('users/reset-password/<int:pk>/', views.UsersResetPassword.as_view(), name='user_reset_password'),
    path('users/create-password/<uuid:uuid>/', views.UsersCreatePassword.as_view(), name='user_create_password'),
]
"""  path('users/', views.UsersViewAll.as_view(), name='users'),
    path('users/<int:pk>/', views.UsersViewUser.as_view(), name='user_view'),
    path('users/edit/<int:pk>/', views.UsersEditUser.as_view(), name='user_edit'),
    path('users/delete/<int:pk>/', views.UsersDeleteUser.as_view(), name='user_delete'),
    path('users/create/', views.UsersCreateUser.as_view(), name='user_create'),
    path('users/invite/', views.UsersInviteUser.as_view(), name='user_invite'),
    path('users/reset-password/<int:pk>/', views.UsersResetPassword.as_view(), name='user_reset_password'),
    path('users/create-password/<uuid:uuid>/', views.UsersCreatePassword.as_view(), name='user_create_password'),
    path('profile/<int:pk>/', views.ProfileViewProfile.as_view(), name='view_profile'), """

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
   pass

class UserProfile(models.Model):
   full_name = models.CharField(max_length=250,null=True,blank=True)
   user = models.OneToOneField(User,on_delete=models.CASCADE)

   def __str__(self):
      return self.full_name

class UserSettings(models.Model):
   owner = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
   
class PasswordToken(models.Model):
    token = models.UUIDField(null=False)
    email = models.EmailField(null=False, blank=False)
    name = models.CharField(max_length=200, null=True)
    last_name = models.CharField(max_length=200, null=True)
    user_id = models.PositiveIntegerField(null=True)
    is_staff = models.BooleanField(null=False, default=False)
    token_life = models.PositiveIntegerField(null=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.token)

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm


from .models import User

class CustomUserModelForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']
        labels = {
            'first_name': 'First name',
            'last_name': 'Last name',
            'email': 'Email',
            'password1': 'Password',
            'password2': 'Confirm password'
        }
  

    def __init__(self, *args, **kwargs):
        super(CustomUserModelForm, self).__init__(*args, **kwargs)
        

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})

users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin

import uuid
from datetime import datetime, timedelta

from users.utils import email_user


from .models import User, UserProfile, PasswordToken

from .forms import CustomUserModelForm

# Create your views here.
class ProfileViewProfile(LoginRequiredMixin, View):
    def get(self, request):
        context = {}
        return render(request, 'users/profile.html')

class ProfileRegisterUser(View):
    def get(self, request):
        form = CustomUserModelForm()
        context = { 'form': form }
        return render(request, 'registration/register.html', context)

class ProfileForgotPassword(View):
    def get(self, request):
        return render(request, 'users/forgot_password.html')

class UsersViewAll(LoginRequiredMixin,View):
    def get(self, request):
        users = list(User.objects.values('id','username', 'email', 'is_staff','first_name'))
        
        context = { 
            'users': users,
            'action': {
                'name': 'User',
                'view_url': 'users:user_view',
                'edit_url': 'users:user_edit',
                'delete_url': 'users:user_delete',
                'create_url': 'users:user_create',
                'invite_url': 'users:user_invite',
            }
        }
        return render(request, 'users/users.html', context)

class UsersViewUser(LoginRequiredMixin,View):
    def get(self, request, pk):
        try:
            user = User.objects.values('id','username', 'email', 'is_staff','first_name','last_name','is_active').get(id=pk)
        
        except:
            messages.error(request, 'User does not exist')
            return redirect('users:view_users')
            
        context = {
            'page': 'view',
            'edit_user': user,
            'next': 'users:view_users'
        }
        return render(request, 'users/edit-user.html', context)

class UsersEditUser(LoginRequiredMixin,View):

    def get(self,request, pk):        
        try:
            user = User.objects.values('id','username', 'email', 'is_staff','first_name','last_name', 'is_active').get(id=pk)
               
        except Exception as err:
            print(err)
            messages.error(request, 'User does not exist')
            return redirect('users:view_users')
            
        context = {
            'page': 'edit',
            'edit_user': user,
            'next': 'users:view_users'
        }
        return render(request, 'users/edit-user.html', context)

    def post(self, request, pk):
        name=request.POST.get('name')
        last_name=request.POST.get('last_name')
        is_admin=request.POST.get('is_admin') 
        is_admin = True if is_admin else False
        is_active=request.POST.get('is_active') 
        is_active = True if is_active else False
        """  is_locked=request.POST.get('is_locked') 
        is_locked = True if is_locked else False """
        if name == "":
            messages.error(request, 'Name cannot be blank.')
            return redirect('users:view_users')
        try:
            user = User.objects.get(id=pk)
        except:
            messages.error(request, 'User does not exist')
            return redirect('users:view_users')
            
        user.first_name = name
        user.last_name = last_name
        user.is_staff = is_admin
        user.is_active = is_active
        #user.is_locked = is_locked
        user.save()
        return redirect('users:view_users')

class UsersDeleteUser(LoginRequiredMixin,View) :
    def delete(self,request, pk):     
        try:
            user = User.objects.filter(id=pk).delete()

        except:
            messages.error(request, 'User not found')
            return redirect('users:view_users')
        users = list(User.objects.values('id','username', 'email', 'is_staff','first_name'))
        
        context = { 
            'users': users,
            'action': {
                'name': 'User',
                'view_url': 'users:user_view',
                'edit_url': 'users:user_edit',
                'delete_url': 'users:user_delete',
                'create_url': 'users:user_create',
                'invite_url': 'users:user_invite',
            }
        }
        return render(request, 'users/partials/list-users.html', context)
    
class UsersCreateUser(LoginRequiredMixin,View):
    def get(self,request):
        context = {
           'next': 'users:view_users'
        }
        return render(request, 'users/create_user.html', context)

    def post(self, request):
        name = request.POST.get('name')
        last_name =request.POST.get('last_name')
        email = request.POST.get('email')
        is_staff = request.POST.get('is_staff')
        is_staff = True if is_staff else False
        #tmp_password = generate_password()
        uuid_str = uuid.uuid4()
        try:
            password_token = PasswordToken(name=name,last_name=last_name, email=email,is_staff=is_staff,token=uuid_str, token_life=1)
            print(password_token)
            password_token.save()
        except Exception as err:
            messages.error(request, 'Error creating password token for new user: ' + str(err))
            return redirect('users:view_users')

        if password_token == None:
            messages.error(request,'Error creating password token for new user.')
            return redirect('users:view_users')
            
        url = 'http://127.0.0.1:8000/users/create-password/' + str(uuid_str) + '?email=' + escape(email) + '&name=' + escape(name)
        html = """\
        Congratulations, """ + name + """!   You're account has been created.  Add your favorite whiskeys to you database, create lists to share with friends and track prices at your favorite stores.

        Please click the link below to activate your account and create a password.

        <a href=""" + url + """ >Activate your account.</a>
        """
        response = email_user(email, html)

        if response['result'] == 0:
            messages.error('Error sending email: ' + str(response['message']))

        return redirect('users:view_users')
class UsersInviteUser(LoginRequiredMixin,View):
    def get(self,request):
        context = {
           'next': 'users:view_users'
        }
        return render(request, 'users/invite_user.html', context)

    def post(self,request):
        name = request.POST.get('name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
            
        user = list(User.objects.filter(email=email).values())

        if len(user) > 1:
            messages.error(request, 'User already exists.')
            return redirect('users:view_users')
        uuid_str = uuid.uuid4()
        try:
            password_token = PasswordToken(name=name,last_name=last_name, email=email,is_staff=False,token=uuid_str, token_life=1)
            print(password_token)
            password_token.save()

        except Exception as err:
            messages.error(request, 'Error creating password token for new user: ' + str(err))
            return redirect('users:view_users')
        if password_token == None:
            messages.error(request,'Error creating password token for new user.')
            return redirect('users:view_users')
            
        url = 'http://127.0.0.1:8000/users/create-password/' + str(uuid_str) + '?email=' + escape(email) + '&name=' + escape(name)+ '&last_name=' + escape(last_name)
        html = """\
        Congratulations, """ + name + """!   You've been invited to join the Whiskey List!  Add your favorite whiskeys to you database, create lists to share with friends and track prices at your favorite stores.

        Please click the link below to activate your account and create a password.

        <a href=""" + url + """ >Activate your account.</a>
        """
        response = email_user(email, html)

        if response['result'] == 0:
            messages.error('Error sending email: ' + str(response['message']))
            
        return redirect('users:view_users')

class UsersResetPassword(View):
    def get(request, pk):
        user = User.objects.get(id=pk)
        
        if user == None:
            messages.error('User not found')
            redirect('users:view_users')

        context = {
            'user': user,
           'next': 'users:view_users'
        }
        return render(request, 'users/reset_password.html', context)

    def post(self, request,pk):
        user = User.objects.get(id=pk)
        
        if user == None:
            messages.error('User not found')
            redirect('users:view_users')
        name = user.first_name
        email = user.email
        user.password_expired = True
        user.save()
            
        uuid_str = uuid.uuid4()
        url = 'http://127.0.0.1:8000/users/create-password/' + str(uuid_str) + '?email=' + escape(email) + '&name=' + escape(name)
        print(url)
        html = """\
        Hello, """ + name + """.   Your password has expired.

        Please click the <a href=""" + url + """>link</a>  to create a new password.
        """
        response = email_user(email, html)

        if response['result'] == 0:
            messages.error('Error sending email: ' + str(response['message']))

        return redirect('users:view_users')
    
class UsersCreatePassword(View):
    def get(self,request, uuid):
        password_token = PasswordToken.objects.get(token=uuid)

        if password_token == None:
            msg = 'Cannot find token.'
            ctx = { 'uuid': uuid, 'name':  request.POST.get('name'),'last_name': request.POST.get('last_name'), 'email':  request.POST.get('email'), 'password': '', 'password_confirm': '','next': 'core:index', 'error': True, 'msg': msg}

users/templates/users/create_password.html
{% extends "navbar.html" %}

{% block content %}
<div class="container">
    <div class="justify-content-center mt-5">
        {% if error %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{msg}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
        <div class="card shadow-sm login-card col-lg-6 col-md-6 col-sm-6 mx-auto" >
            <div class="card-header">
                Create Password
            </div>
            <div class="card-body  ">
                <form  method="POST" action="{% url 'users:user_create_password' uuid %}">
                    {% csrf_token %}
                    
                    <div class="form-outline mb-4">
                        <name class="form-label" for="name">First Name</name>
                        <input type="text" id="name" name="name" class="form-control" value="{{name}}" required/>
                    </div>

                    <div class="form-outline mb-4">
                        <name class="form-label" for="last_name">Last Name</name>
                        <input type="text" id="last_name" name="last_name" class="form-control" value="{{last_name}}" required/>
                    </div>
                
                    <div class="form-outline mb-4">
                        <name class="form-label" for="email">Email</name>
                        <input type="text" id="email" name="email" class="form-control" value="{{email}}" disabled/>
                    </div>

                    <div class="form-outline mb-4">
                        <name class="form-label" for="password">Password</name>
                        <input type="password" id="password" name="password" class="form-control"  value="{{password}}" placeholder="Enter Password..." required/>
                    </div>

                    <div class="form-outline mb-4">
                        <name class="form-label" for="password_confirm">Confirm Password</name>
                        <input type="password" id="password_confirm" name="password_confirm" class="form-control"  value="{{password_confirm}}" placeholder="Confirm Password..." required/>
                    </div>

                    <!-- Submit button -->
                    
                    <button type="submit" class="btn btn-primary btn-block mb-4">Create</button>
                    <a href="{% url next %}" class="btn btn-danger btn-block mb-4">Cancel</a>
                    
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/create_user.html
{% extends "navbar.html" %}

{% block content %}
<div class="container">
    <div class="justify-content-center mt-5">
        
        <div class="card shadow-sm login-card col-lg-6 col-md-6 col-sm-6 mx-auto" >
            <div class="card-header">
                Create User
            </div>
            <div class="card-body  ">
                <form  method="POST" action="{% url 'users:user_create'  %}">
                    {% csrf_token %}
                    
                    <div class="form-outline mb-4">
                        <name class="form-label" for="name">First Name</name>
                        <input type="text" id="name" name="name" class="form-control" placeholder="Enter First Name..." required autofocus/>
                    </div>

                    <div class="form-outline mb-4">
                        <name class="form-label" for="last_name">Last Name</name>
                        <input type="text" id="last_name" name="last_name" class="form-control" placeholder="Enter Last Name..." required/>
                    </div>
                
                    <div class="form-outline mb-4">
                        <name class="form-label" for="email">Email</name>
                        <input type="text" id="email" name="email" class="form-control" placeholder="Enter Email..." required/>
                    </div>

                    <div class="form-outline mb-4 form-check">
                        <input class="form-check-input" type="checkbox" value="admin" name="is_admin" id="is_admin" >
                        <label class="form-check-label" for="is_admin">
                          Admin
                        </label>
                      </div>
                    <!-- Submit button -->
                    
                    <button type="submit" class="btn btn-primary btn-block mb-4">Create</button>
                    <a href="{% url next %}" class="btn btn-danger btn-block mb-4">Cancel</a>
                    
                    
                    
                    
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/edit-user.html
{% extends "navbar.html" %}

{% block content %}
<div class="container">
    <div class="justify-content-center mt-5">
        
        <div class="card shadow-sm login-card col-lg-6 col-md-6 col-sm-6 mx-auto" >
            <div class="card-header">
                {% if page == 'edit' %}Edit{% endif %} User
            </div>
            <div class="card-body  ">
                <form  method="POST" action="{% url 'users:user_edit' edit_user.id %}">
                    {% csrf_token %}
                    
                    <div class="form-outline mb-4">
                        <name class="form-label" for="name">First Name</name>
                        <input type="text" id="name" name="name" class="form-control" value="{{edit_user.first_name}}" {% if page == 'view' %} disabled {% else %} autofocus {% endif %}/>
                    </div>

                    <div class="form-outline mb-4">
                        <name class="form-label" for="name">Last Name</name>
                        <input type="text" id="last_name" name="last_name" class="form-control" value="{{edit_user.last_name}}" {% if page == 'view' %} disabled  {% endif %}/>
                    </div>
                
                    <div class="form-outline mb-4">
                        <name class="form-label" for="username">Username</name>
                        <input type="text" id="username" name="username" class="form-control" value="{{edit_user.username}}" disabled/>
                    </div>
                    <div class="form-outline mb-4">
                        <name class="form-label" for="email">Email</name>
                        <input type="text" id="email" name="email" class="form-control" value="{{edit_user.email}}" disabled/>
                    </div>
                    <div class="form-outline mb-4 form-check">
                        <input class="form-check-input" type="checkbox" value="admin" name="is_admin" id="is_admin" {% if edit_user.is_staff %} checked {% endif %} {% if page == 'view' %} disabled {% endif %}>
                        <label class="form-check-label" for="is_admin">
                          Admin
                        </label>
                    </div>
                    <div class="form-outline mb-4 form-check">
                        <input class="form-check-input" type="checkbox" value="active" name="is_active" id="is_active" {% if edit_user.is_active %} checked {% endif %} {% if page == 'view' %} disabled {% endif %}>
                        <label class="form-check-label" for="is_active">
                          Active
                        </label>
                    </div>
                    <div class="form-outline mb-4 form-check">
                        <input class="form-check-input" type="checkbox" value="locked" name="is_locked" id="is_locked" {% if edit_user.is_locked %} checked {% endif %} {% if page == 'view' %} disabled {% endif %}>
                        <label class="form-check-label" for="is_locked">
                          Locked
                        </label>
                    </div>

                    <!-- Submit button -->
                    {% if page == 'edit' %}
                    <button type="submit" class="btn btn-primary btn-block mb-4">Update</button>
                    <a href="{% url next %}" class="btn btn-danger btn-block mb-4">Cancel</a>
                    {% else %}
                    <div class="edit-user-action">
                        <a href="{% url 'users:user_edit' edit_user.id %}" class="btn btn-success btn-block mb-4">Edit User</a> <a href="{% url 'users:user_reset_password' edit_user.id %}" class="btn btn-danger btn-block mb-4">Reset Password</a> <a href="{% url next %}" class="btn btn-primary btn-block mb-4">Go Back</a>
                    </div>
                    {% endif %}
                    
                    
                    
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/forgot_password.html
{% extends "navbar.html" %}

{% block content %}
<div class="container">
    <div class="justify-content-center mt-5">
        
        <div class="card shadow-sm login-card col-lg-6 col-md-6 col-sm-6 mx-auto" >
            <div class="card-header">
                Forgot password
            </div>
            <div class="card-body  ">
                {% if form.errors %}
                    <p>Error</p>
                {% endif %}
                <form  method="POST" action="{% url 'users:forgot_password' %}">
                    {% csrf_token %}
                    
                    <div class="line mb-4">
                        <label for="formInput#email">Email Address: </label>
                        <input
                        class="form-control"
                        id="formInput#email"
                        type="email"
                        name="email"
                        placeholder="e.g. user@domain.com"
                        required
                        />
                    </div>
                    
                    <!-- Submit button -->
                    <button type="submit" class="btn btn-primary btn-block mb-4">Reset password</button>
                    
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/invite_user.html
{% extends "navbar.html" %}

{% block content %}
<div class="container">
    <div class="justify-content-center mt-5">
        
        <div class="card shadow-sm login-card col-lg-6 col-md-6 col-sm-6 mx-auto" >
            <div class="card-header">
               Invite User
            </div>
            <div class="card-body  ">
                <form  method="POST" action="{% url 'users:user_invite' %}">
                    {% csrf_token %}
                    
                    <div class="form-outline mb-4">
                        <name class="form-label" for="name">Name</name>
                        <input type="text" id="name" name="name" class="form-control" placeholder="Enter Name..." autofocus required/>
                    </div>

                    <div class="form-outline mb-4">
                        <name class="form-label" for="last_name">Last Name</name>
                        <input type="text" id="last_name" name="last_name" class="form-control" placeholder="Enter Last Name..." required/>
                    </div>
                
                    <div class="form-outline mb-4">
                        <name class="form-label" for="email">Email</name>
                        <input type="text" id="email" name="email" class="form-control" placeholder="Enter Email..." required/>
                    </div>

                    <!-- Submit button -->
                    
                    <button type="submit" class="btn btn-primary btn-block mb-4">Invite</button>
                    <a href="{% url next %}" class="btn btn-danger btn-block mb-4">Cancel</a>
                    
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends "navbar.html" %}

{% block content %}
<section class="text-gray-600 body-font relative">
  <div class="container px-5 py-15 mx-auto">
    
    <div class="lg:w-1/2 md:w-2/3 mx-auto">
        <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">Settings</h1>
       <hr>
        <div class="row" id="user-settings">
        <div id="information" ></div>
        {% include 'users/partials/settings.html' %}
        </div>
        </div>
       
    </div>
  </div>
</section>

{% endblock %}

users/templates/users/reset_password.html
{% extends "navbar.html" %}

{% block content %}
<div class="container">
    <div class="justify-content-center mt-5">
        
        <div class="card shadow-sm login-card col-lg-6 col-md-6 col-sm-6 mx-auto" >
            <div class="card-header">
              Reset User's Password
            </div>
            <div class="card-body  ">
                <form  method="POST" action="{% url 'users:user_reset_password' user.id %}">
                    {% csrf_token %}
                    
                    <div class="form-outline mb-4">
                        <name class="form-label" for="name">Name</name>
                        <input type="text" id="name" name="name" class="form-control" value="{{user.first_name}}" disabled/>
                    </div>
                
                    <div class="form-outline mb-4">
                        <name class="form-label" for="email">Email</name>
                        <input type="text" id="email" name="email" class="form-control" value="{{user.email}}" disabled />
                    </div>

                    <!-- Submit button -->
                    
                    <button type="submit" class="btn btn-primary btn-block mb-4">Reset Password</button>
                    <a href="{% url next %}" class="btn btn-danger btn-block mb-4">Cancel</a>
                    
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/users.html
{% extends "navbar.html" %}

{% block content %}
    <div class="container">
        <div class="justify-content-center mt-5">
            <div class="col">
                <h1>Users</h1>
                <hr>
                {% include 'components/add_action_buttons.html' with name=action.name create_view=action.create_url invite_view=action.invite_url %}
                <hr>
                <div class="row">
                    <div class="col" id="user-list">
                        {% include 'users/partials/list-users.html' %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}