core/urls.py
from django.contrib import admin
from django.urls import path

from core import views

app_name = 'core'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),

]

rPiManager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls', namespace='core')),
    path('', include('users.urls', namespace='users')),
    path('', include('rpi.urls', namespace='rpi')),
    

]

rpi/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'rpi'

urlpatterns = [
   path('models/', views.rPiModelsList.as_view(), name='view_models'), 
   path('models/add-model/', views.rPiModelsAdd.as_view(), name='add_model'), 
   path('models/edit/<int:pk>', views.rPiModelsEdit.as_view(), name='edit_model'), 
   path('models/delete/<int:pk>', views.rPiModelsDelete.as_view(), name='delete_model'), 

   path('rpis/', views.rPiList.as_view(), name='view_rpis'), 
   path('rpis/add', views.rPiAdd.as_view(), name='add_rpi'), 
   path('rpis/<int:pk>', views.rPiViewrPi.as_view(), name='view_rpi'), 
   path('rpis/edit/<int:pk>', views.rPiEdit.as_view(), name='edit_rpi'), 
   path('rpis/delete/<int:pk>', views.rPiDelete.as_view(), name='delete_rpi'), 
   path('rpis/settings/<int:pk>', views.rPiSettings.as_view(), name='rpi_settings'), 
   path('rpis/deploy/<int:pk>', views.rPiDeploy.as_view(), name='rpi_deploy'), 
   path('rpis/search', views.rPiSearch.as_view(), name='rpi_search'), 
   path('rpis/check-in/<int:pk>', views.rPiCheckin.as_view(), name='rpi_checkin'), 
   path('rpis/key/upload/<int:pk>', views.rPiUploadKey.as_view(), name='rpi_upload_key'), 
   path('rpis/key/downlaod/<int:pk>', views.rPiDownloadKey.as_view(), name='rpi_download_key'), 
   path('rpis/deployed/', views.rPiDeployed.as_view(), name='rpi_deployed'), 
   path('rpis/deployed/search', views.rPiDeployedSearch.as_view(), name='rpi_deployed_search'), 
   path('rpis/connect/<int:pk>', views.rPiConnect.as_view(), name='rpi_connect'), 

   path('locations/', views.rPiViewLocations.as_view(), name='view_locations'), 
   path('locations/<int:pk>', views.rPiViewLocation.as_view(), name='view_location'), 
   path('locations/add/', views.rPiAddLocation.as_view(), name='add_location'), 
   path('locations/edit/<int:pk>', views.rPiEditLocation.as_view(), name='edit_location'), 
   path('locations/delete/<int:pk>', views.rPiDeleteLocation.as_view(), name='delete_location'),
   path('locations/search', views.rPiSearchLocation.as_view(), name='search_location'),
]
    
    

users/urls.py
from django.contrib import admin
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
   path('profile/', views.ProfileViewProfile.as_view(), name='view_profile'), 
   path('register/', views.ProfileRegisterUser.as_view(), name='register_user'),
   path('forgot-password/', views.ProfileForgotPassword.as_view(), name='forgot_password'),
   path('users/', views.UsersViewAll.as_view(), name='view_users'),
    path('users/<int:pk>/', views.UsersViewUser.as_view(), name='user_view'),
    path('users/edit/<int:pk>/', views.UsersEditUser.as_view(), name='user_edit'),
    path('users/delete/<int:pk>/', views.UsersDeleteUser.as_view(), name='user_delete'),
    path('users/create/', views.UsersCreateUser.as_view(), name='user_create'),

    path('users/invite/', views.UsersInviteUser.as_view(), name='user_invite'),
    path('users/reset-password/<int:pk>/', views.UsersResetPassword.as_view(), name='user_reset_password'),
    path('users/create-password/<uuid:uuid>/', views.UsersCreatePassword.as_view(), name='user_create_password'),
]
"""  path('users/', views.UsersViewAll.as_view(), name='users'),
    path('users/<int:pk>/', views.UsersViewUser.as_view(), name='user_view'),
    path('users/edit/<int:pk>/', views.UsersEditUser.as_view(), name='user_edit'),
    path('users/delete/<int:pk>/', views.UsersDeleteUser.as_view(), name='user_delete'),
    path('users/create/', views.UsersCreateUser.as_view(), name='user_create'),
    path('users/invite/', views.UsersInviteUser.as_view(), name='user_invite'),
    path('users/reset-password/<int:pk>/', views.UsersResetPassword.as_view(), name='user_reset_password'),
    path('users/create-password/<uuid:uuid>/', views.UsersCreatePassword.as_view(), name='user_create_password'),
    path('profile/<int:pk>/', views.ProfileViewProfile.as_view(), name='view_profile'), """

templates/main.html
{% load static i18n %}

<!DOCTYPE html>  
<html lang="en">  
<head>  
     <!-- Required meta tags -->
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
 
    <title>{{ settings.APP_NAME }}</title>  
    
    <script src="https://kit.fontawesome.com/11129ed0f0.js" crossorigin="anonymous"></script>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <script src="https://unpkg.com/htmx.org@1.7.0" integrity="sha384-EzBXYPt0/T6gxNp0nuPtLkmRpmDBbjg6WmCUZRLXBBwYYmwAUxzlSGej0ARHX0Bo" crossorigin="anonymous" defer></script>
    <script defer src="https://unpkg.com/alpinejs@3.10.2/dist/cdn.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" />
    
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>  
<body> 
        
                 <div class="row ms-1 me-1">
                        {% block navbar %}{% endblock %}
                </div>
        <div class="container" >
                <div class="row" >
                        {% if messages %}
                        <ul class="messages">
                                {% for message in messages %}
                                <li{% if message.tags %} class="{{message.tags}}"{% endif %}>{{ message }}</li>
                                {% endfor %}
                        </ul>
                        {% endif %} 
                        {% block content %}{% endblock %}
                </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        
        
        <script>
                document.body.addEventListener('htmx:configRequest', (event) => {
                event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}'; })
        </script>
</bod>

</html>  

templates/navbar.html
{% extends "main.html" %}
{% load static %}
{% block navbar %}
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'core:index' %}"><i class="fab fa-raspberry-pi "></i> Manager</a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      {% if user.is_authenticated %}
      <li class ="nav-item">
        <a class="nav-link" href="{% url 'core:index' %}">Dashboard</a>
      </li>
      {% else %}
       <li class ="nav-item">
        <a class="nav-link" href="{% url 'core:index' %}">Home</a>
       </li>
      {% endif %}
      {% if user.is_authenticated %}
      <li class ="nav-item">
          <a class="nav-link" href="{% url 'rpi:view_rpis' %}">Raspberry Pis</a>
      </li>
      <li class ="nav-item">
          <a class="nav-link"  href="{% url 'rpi:rpi_deployed' %}">Deployed</a>
      </li>
      {% endif %}

    </ul>
    

    <div class="navbar-collapse  " id="navbarNavDarkDropdown">
      {% if user.is_authenticated  %}
          <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Admin
            </a>
            <ul class="dropdown-menu dropdown-menu" aria-labelledby="navbarDarkDropdownMenuLink">
              <li class ="nav-item">
                <a class="dropdown-item" href="{% url 'rpi:view_models'  %}">rPi Models</a>
              </li>
              <li class ="nav-item">
                <a class="dropdown-item" href="{% url 'rpi:view_locations'  %}">Locations</a>
              </li>
              <li class ="nav-item">
                <a class="dropdown-item" href="{% url 'users:view_users'  %}">Users</a>
              </li>
              <li class ="nav-item">
                <a class="dropdown-item" href="{% url 'rpi:view_models'  %}">API Keys</a>
              </li>
              
            
            </ul>
          </li>
       
        </ul>
      {% endif %}
      </div>
      <div class="navbar-collapse justify-content-end " id="navbarNavDarkDropdown">
      <ul class="navbar-nav">
        {% if  user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Account
            </a>
            <ul class="dropdown-menu dropdown-menu" aria-labelledby="navbarDarkDropdownMenuLink">
              <li class ="nav-item">
                <a class="dropdown-item" href="">Settings</a>
              </li>
              <li class ="nav-item">
                <a class="dropdown-item" href="{% url 'logout' %}?next={% url 'core:index' %}">Logout</a>
              </li>
            
            </ul>
          </li>
        {% else %}
          <li class ="nav-item">
            <a class="nav-link" href="{% url 'login' %}?next={% url 'core:index' %}">Login</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>


</nav>

{% endblock %}